# Generated by Django 4.1.4 on 2023-02-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('cnic', models.BigIntegerField(unique=True)),
                ('father_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('token_number', models.IntegerField(unique=True)),
                ('prescription', models.TextField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patient')),
            ],
        ),
    ]
