# Generated by Django 4.1.4 on 2023-02-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='id',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='token_number',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
