# Generated by Django 4.1.4 on 2023-02-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_prescription_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'New Patient', 'verbose_name_plural': 'New Patient'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Existing Patient', 'verbose_name_plural': 'Existing Patient'},
        ),
    ]
